# Website settings
url: "https://www.foluwa.github.io"

# Internal nav
nav:
  main:
#    about: "/about"
#    writing: "/writing"
    blog: "/blog/"
    projects: "/projects/"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Moronfoluwa Akintola"
description: "Moronfoluwa Akintola is a software engineer with 3+ years’ experience. He seeks to leverage solid skills in artificial intelligence and cross-platform software development. He is passionate about software engineering and community building, this has introduced him to many technical communities like Google Developer Students Clubs and Andela Learning Community.&quot;"
thumbnail_path: "profile-photos/moronfoluwa-akintola-medium.png"
# bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
# hello_startup_url: "https://www.hello-startup.net/"
# website_repo_url: "https://github.com/Foluwa/Foluwa.github.io"
# atomic_squirrel_url: "https://www.atomic-squirrel.net/"
# gruntwork_url: "https://www.gruntwork.io/"
# terraform_up_and_running_url: "https://www.terraformupandrunning.com/"
# terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/fantasticfoluwa"
    label: "Twitter"
    icon: "twitter-square"
    username: "@fantasticfoluwa"
  linkedin:
    url: "https://www.linkedin.com/in/moronfoluwaakintola/"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/akintola.moronfoluwar"
    label: "Facebook"
    icon: "facebook-square"
  github:
    url: "https://github.com/foluwa/"
    label: "GitHub"
    icon: "github-square"
  reddit:
    url: "https://www.reddit.com/user/Foluwa120"
    label: "Reddit"
    icon: "reddit-square"
  email:
    url: "mailto:moronfoluwaakintola@gmail.com"
    label: "Email"
    value: "moronfoluwaakintola@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/blog/page:num"
permalink: "/blog/:title/"  #"/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: Foluwa/Foluwa.github.io
color: "#fff"
url: "/"

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
